Bug 691: return "exit 1" to traps but dont trap signal 0 anymore.

diff --git a/etc/faxaddmodem.sh.in b/etc/faxaddmodem.sh.in
--- a/etc/faxaddmodem.sh.in
+++ b/etc/faxaddmodem.sh.in
@@ -254,7 +254,7 @@ while [ -z "$TTY" -o ! -c /dev/$TTY ]; do
 done
 
 JUNK="$OUT"
-trap "$RMCMD \$JUNK; $RMCMD -r $TMPDIR" 0 1 2 15
+trap "$RMCMD \$JUNK; $RMCMD -r $TMPDIR; exit 1" 1 2 15
 
 if [ ! -d $UUCP_LOCKDIR ]; then
     cat<<EOF
@@ -875,7 +875,7 @@ while [ -z "$RESULT" ]; do
 	echo ""
 	echo "Hmm, something seems to be hung, check your modem eh?"
      done)& nagpid=$!
-    trap "$RMCMD \$JUNK; $RMCMD -r $TMPDIR; kill $nagpid \$catpid" 0 1 2 15
+    trap "$RMCMD \$JUNK; $RMCMD -r $TMPDIR; kill $nagpid \$catpid; exit 1" 1 2 15
     SendToModem "AT+FCLASS=?" 			# ask for class support
 
     exec 3>&2 2> /dev/null  # Mute stderr against child death
@@ -883,7 +883,7 @@ while [ -z "$RESULT" ]; do
     wait $nagpid            # Really waits its end
     exec 2>&3 3>&-          # Restore stderr
 
-    trap "$RMCMD \$JUNK; $RMCMD -r $TMPDIR; test \"\$catpid\" && kill \$catpid" 0 1 2 15
+    trap "$RMCMD \$JUNK; $RMCMD -r $TMPDIR; test \"\$catpid\" && kill \$catpid; exit 1" 1 2 15
     sleep 1
 
     RESULT=`tr -ds '\015' '\012' < $OUT | $SED -n '$p'`
@@ -2019,3 +2019,7 @@ echo "Don't forget to run faxmodem(@MANNUM1_8@) (if you have a send-only environ
 echo "or configure init to run faxgetty on $TTY."
 
 exec >/dev/null 2>&1
+
+# cleanup
+$RMCMD $JUNK; $RMCMD -r $TMPDIR
+exit 0
diff --git a/etc/probemodem.sh.in b/etc/probemodem.sh.in
--- a/etc/probemodem.sh.in
+++ b/etc/probemodem.sh.in
@@ -128,7 +128,7 @@ done
 # Lock the device for later use when deducing the modem type.
 #
 JUNK="$LOCKX $OUT"
-trap "@RM@ -f $JUNK; @RM@ -fr $TMPDIR" 0 1 2 15
+trap "@RM@ -f $JUNK; @RM@ -fr $TMPDIR; exit 1" 1 2 15
 
 LOCKSTR=`expr "         $$" : '.*\(..........\)'`
 # lock the device by all of its names
@@ -270,7 +270,7 @@ while [ -z "$RESULT" ]; do
 	echo ""
 	echo "Hmm, something seems to be hung, check your modem eh?"
      done)& nagpid=$!
-    trap "@RM@ -f \$JUNK; @RM@ -fr $TMPDIR; kill $nagpid \$catpid" 0 1 2 15
+    trap "@RM@ -f \$JUNK; @RM@ -fr $TMPDIR; kill $nagpid \$catpid; exit 1" 1 2 15
 
     if [ x"$ATCMD" != x"" ]; then
 	SendToModem "$ATCMD"
@@ -283,7 +283,7 @@ while [ -z "$RESULT" ]; do
     wait $nagpid		# Really waits its end
     exec 2>&3 3>&-		# Restore stderr
 
-    trap "@RM@ -f \$JUNK; @RM@ -fr $TMPDIR; test \"\$catpid\" && kill \$catpid" 0 1 2 15
+    trap "@RM@ -f \$JUNK; @RM@ -fr $TMPDIR; test \"\$catpid\" && kill \$catpid; exit 1" 1 2 15
     sleep 1
 
     RESULT=`tr -ds '\015' '\012' < $OUT | $SED -n '$p'`
@@ -510,7 +510,9 @@ echo ""
 if [ "$ATCMD" != "" ]; then
     echo "The response was: $RESPONSE"
     echo "The result was  : $RESULT"
-    exit
+    # cleanup
+    @RM@ -f $JUNK; @RM@ -fr $TMPDIR
+    exit 0
 fi
 if [ "$RESULT" = "OK" ]; then
     # Looks like a usable fax modem.  Get more information.
@@ -539,7 +541,9 @@ if [ "$RESULT" = "OK" ]; then
 	cat $OUT
 	echo ""
 	echo "I don't figure that it's worthwhile to continue..."
-	exit
+	# cleanup
+	@RM@ -f $JUNK; @RM@ -fr $TMPDIR
+	exit 0
     else
 	common
 	for CLASS in $MODEMCLASSES; do
@@ -554,5 +558,9 @@ if [ "$RESULT" = "OK" ]; then
     fi
 else
     echo "This not a Class 1, 2, 2.0, 1.0, or 2.1 modem."
-    exit
 fi
+
+# cleanup
+@RM@ -f $JUNK; @RM@ -fr $TMPDIR
+exit 0
+
diff --git a/util/faxcron.sh.in b/util/faxcron.sh.in
--- a/util/faxcron.sh.in
+++ b/util/faxcron.sh.in
@@ -93,7 +93,7 @@ while [ x"$1" != x"" ] ; do
     shift
 done
 
-trap "$RM \$AWKTMP \$JUNK; $RM -rf $TMPDIR" 0 1 2 15
+trap "$RM \$AWKTMP \$JUNK; $RM -rf $TMPDIR; exit 1" 1 2 15
 
 
 test -z "$LASTRUN" && LASTRUN=`$CAT $LAST 2>/dev/null`
@@ -472,3 +472,7 @@ if [ -s $JUNK ]; then
 fi
 
 $RM $LAST; eval $UPDATE
+
+# cleanup
+$RM $AWKTMP $JUNK; $RM -rf $TMPDIR
+exit 0
