Add templated version of notify, using common-functions

diff --git a/util/common-functions.sh.in b/util/common-functions.sh.in
--- a/util/common-functions.sh.in
+++ b/util/common-functions.sh.in
@@ -69,17 +69,15 @@ parseQfile()
     # inside such strings and must be put outside of them. We thus replace
     # (') with ('\'') which terminates the current string, adds a single
     # quote and starts a new string.
-    #
-    # New lines in eval could cause problems so we escape them. As with
-    # single quotes above, we must first close the current string, add
-    # the escaped new line (double quoted) and start a new string.
+#
+    # We no longer escape newlines, because we don't eval
     #
     # print out variable name and value so we can eval it in the shell
-    eval `($AWK -F: ' 
+    #
+    eval "`($AWK -F: ' 
     function p(varname,val)
     {
         gsub(/\\047/, "\047\\\\\047\047", val);
-        gsub(/\n/, "\047\042\\\\n\042\047", val);
         printf "%s=\\047%s\\047\n",varname,val
         printf "export %s\n",varname
     }
@@ -144,23 +142,22 @@ parseQfile()
     /^page:/    { p("pins_"++npins, $4); }
     /^data:/    { p("files_"++nfiles, $4); }
     /^poll/        { p("poll", " -p"); }
-    END { p("nfiles", nfiles); p("npins", npins) } ' $QFILE )`
+    END { p("nfiles", nfiles); p("npins", npins) } ' $QFILE )`"
 
 }
 
 parseFaxInfo()
 {
     # We use the same basic stuff as parseQfile(), but just to straight assignment
-    eval `$INFO -S '' -s '%s=!=!=!=!=!=!=!=!=' $1 | $AWK -F'=!=!=!=!=!=!=!=!=' '
+    eval "`$INFO -S '' -s '%s=!=!=!=!=!=!=!=!=' $1 | $AWK -F'=!=!=!=!=!=!=!=!=' '
     function p(varname,val)
     {
         gsub(/\\047/, "\047\\\\\047\047", val);
-        gsub(/\n/, "\047\042\\\\n\042\047", val);
         printf "%s=\\047%s\\047\n",varname,val
         printf "export %s\n",varname
     }
     { p(toupper($1),$2); }
-    '`
+    '`"
 }
 
 #
@@ -269,3 +266,131 @@ CreateMailMessage ()
 	echo "--$MIMEBOUNDARY--"
     fi
 }
+
+
+## A Simple function to trace stuff
+## to STDERR, not STDOUT
+TraceLog ()
+{
+    echo $* 1>&2
+}
+
+## ConvertFile <file> <oldtype> <newtype>
+## Convert $1 from $2 to type $3
+##
+## This will (possibly) create a tempoary file
+## in the Private $TMPDIR area for the new file
+## If the original file is in the proper form, no
+## new file will be created
+##
+## It prints the file name of the converted
+## file to stdout
+ConvertFile ()
+{
+    case "$3" in
+	PostScript|postscript|PS|ps)
+	    TraceLog "Converting $1 to Postscript"
+	    case $2 in
+		PostScript|Postscript|PS|ps)
+		    TraceLog "No conversion"
+		    echo $1
+		    ;;
+		PDF|pdf)
+		    TraceLog "pdf2ps necessary"
+		    name="`basename $1 .pdf`"
+		    $PDF2PS $1 $TMPDIR/$name.ps
+		    echo "$TMPDIR/$name.ps"
+		    ;;
+	    	TIFF|tiff|TIF|tif)
+		    TraceLog "tiff2ps necessary"
+		    name="`basename $1 .tif`"
+		    $TIFF2PS -a $1 > $TMPDIR/$name.ps
+		    echo "$TMPDIR/$name.ps"
+		    ;;
+	    esac
+	    ;;
+	PDF|pdf)
+	    TraceLog "Converting $1 to PDF"
+	    case $2 in
+	    	PostScript|Postscript|PS|ps)
+		    TraceLog "Using ps2pdf"
+		    name="`basename $1 .ps`"
+		    $PS2PDF $1 $TMPDIR/$name.pdf
+		    echo "$TMPDIR/$name.pdf"
+		    ;;
+		PDF|pdf)
+		    TraceLog "Nothing necessary"
+		    ;;
+		TIFF|tiff|TIF|tif)
+		    TraceLog "Using tiff2pdf"
+		    name="`basename $1 .tif`" $TIFF2PDF  -o $TMPDIR/$name.pdf $1 echo "$TMPDIR/$name.pdf"
+	    esac
+	    ;;
+	TIFF|TIF|tif|tiff)
+	    TraceLog "Converting $1 to TIFF"
+	    case $2 in 
+	    	PostScript|Postscript|PS|ps)
+		    TraceLog "Using ps2fax"
+		    name="`basename $1 .ps`"
+		    $PS2FAX -r $resolution $1 $TMPDIR/$name.tif
+		    echo "$TMPDIR/$name.tif"
+		    ;;
+	    	PDF|pdf)
+		    TraceLog "Using pdf2fax"
+		    name="`basename $1 .pdf`"
+		    $PDF2FAX -r $resolution $1 $TMPDIR/$name.tif
+		    echo "$TMPDIR/$name.tif"
+		    ;;
+		TIFF|tiff|TIF|tif)
+		    TraceLog "Nothing neccessary"
+		    ;;
+	    esac
+	    ;;
+	*)
+	    TraceLog "Ignoring $1 to \"$3\""
+	    ;;
+    esac
+
+}
+
+LocalSequence ()
+{
+    if [ $1 -gt $2 ]; then
+	    return
+    fi
+    COUNT=$1
+    while [ $COUNT -le $2 ]
+    do
+	echo $COUNT
+	COUNT=`expr $COUNT + 1`
+    done
+}
+
+SetupPrivateTmp()
+{
+    TMPDIR="/tmp/tmp-$$"
+
+    mkdir -m 0700 "$TMPDIR"
+    if [ $? != 0 ]
+    then
+	echo "Couldn't setup private temp area - exiting!" 1>&2
+	exit 1
+    fi
+}
+
+CleanupPrivateTmp ()
+{
+    if [ -d "$TMPDIR" ]
+    then
+	case "$TMPDIR" in
+	    "/tmp/tmp-$$")
+		rm -Rf "$TMPDIR"
+		;;
+	    *)
+		echo "Cleanup of temporary dir fail: Bad dir $TMPDIR" 1>&2
+		;;
+	esac
+    fi
+}
+
+
